property:
  test: 'hajox'
server:
  port: 8080
  
spring:
  application:
    name: gateway-server
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: 'true'
          lower-case-service-id: 'true'
        
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
