server:
  port: 8082

spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5433/microsevice_register_demo

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: sasdsahxcuajhdcafhsgdjsfdsfskudf
  expiration: 600000
  header: Authorization