server:
  port: 8083

spring:

  
#mail properties
  mail:
    host: smtp.gmail.com
    port: 587
    username: 2021JavaForTest@gmail.com
    password: forTest2021
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

 #postgreSql properties
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://localhost:5433/mail_db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  #flyway properties
  flyway:
    user: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/mail_db
    driver-class-name: org.postgresql.Driver
    validate-on-migrate: false
    baseline-on-migrate: true

