server:
  port: 8085

app:
  service:
    name: User Service Core Application

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/user_service_rest
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
