server:
  port: 8085

app:
  service:
    name: User Service Core Application

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
